export enum ENV_KEY {
    JR_TOKEN = 'JR_TOKEN',
    JR_MAIL = 'JR_MAIL',
    JR_SPACE = 'JR_SPACE',
    DEFAULD_PROJECT_ID = 'DEFAULD_PROJECT_ID',
    DEFAULD_PROJECT_NAME = 'DEFAULD_PROJECT_NAME',
    CURRENT_SPRINT = 'CURRENT_SPRINT',
    CURRENT_SPRINT_ID = 'CURRENT_SPRINT_ID',
    CURRENT_SPRNT_DATE = 'CURRENT_SPRINT_DATE',
    CURRENT_SPRNT_GOAL = 'CURRENT_SPRNT_GOAL',
    LAN ='LAN'
  }