export enum ENV_KEY {
  JR_TOKEN = 1,
  JR_MAIL = 2,
  JR_SPACE = 3,
  DEFAULD_PROJECT_ID = 4,
  DEFAULD_PROJECT_NAME = 5,
  DEFAULD_PROJECT_TYPE = 25,
  CURRENT_SPRINT = 6,
  CURRENT_SPRINT_ID = 7,
  CURRENT_SPRNT_DATE = 8,
  CURRENT_SPRNT_GOAL = 9,
  LAN = 10,
  SMART_URL = 11,
  SMART_EMAIL = 12,
  SMART_ACCESS = 13,
  SMART_TOKEN = 14,
  SMART_USER_ID = 15,
  SMART_USER_NAME = 16,
  SMART_DEFAULD_PROJECT_ID = 17,
  SMART_DEFAULD_PROJECT_NAME = 18,
  SMART_DEFAULD_TASK_TYPE = 19, 
  SMART_DEFAULD_TASK_TYPE_NAME = 20, 
  SMART_DEFAULD_RQ_ID = 21,
  SMART_DEFAULD_RQ_NAME = 22,
  SMART_DEFAULD_CAT_ID = 23,
  SMART_DEFAULD_CAT_NAME = 24,
  ISSUES = 26
}


export enum LANGUAGES {
  EN = 'EN',
  ES = 'ES'
}

export enum DB_NAME {
  JIRA_PROJECTS = 'jira_projects',
  SMART_PROJECTS = 'smart_projects',
  JIRA_SPACES = 'jira_spaces'
}