export enum ENV_KEY {
    JR_TOKEN = 'JR_TOKEN',
    JR_MAIL = 'JR_MAIL',
    JR_SPACE = 'JR_SPACE',
    DEFAULD_PROJECT_ID = 'DEFAULD_PROJECT_ID',
    DEFAULD_PROJECT_NAME = 'DEFAULD_PROJECT_NAME',
    CURRENT_SPRINT = 'CURRENT_SPRINT',
    CURRENT_SPRINT_ID = 'CURRENT_SPRINT_ID',
    CURRENT_SPRNT_DATE = 'CURRENT_SPRINT_DATE',
    CURRENT_SPRNT_GOAL = 'CURRENT_SPRNT_GOAL',
    LAN ='LAN',
    SMART_URL = 'SMART_URL',
    SMART_TOKEN = 'SMART_TOKEN',
    SMART_USER_ID = 'SMART_USER_ID',
    SMART_USER_NAME = 'SMART_USER',
    SMART_DEFAULD_PROJECT_ID = 'SMART_DEFAULD_PROJECT',
    SMART_DEFAULD_PROJECT_NAME = 'SMART_DEFAULD_PROJECT_NAME',
    SMART_DEFAULD_TASK_TYPE = 1, // REGULAR
    SMART_DEFAULD_TASK_TYPE_NAME = 'Regular',
    SMART_DEFAULD_RQ_ID = 'SMART_DEFAULD_PROJECT',
    SMART_DEFAULD_RQ_NAME = 'SMART_DEFAULD_PROJECT_NAME',
    SMART_DEFAULD_CAT_ID = 'SMART_DEFAULD_PROJECT',
    SMART_DEFAULD_CAT_NAME = 'SMART_DEFAULD_PROJECT_NAME'
  }